version: '2'

services:
    node:
        container_name: node-typescript
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/home/nodets
            - /home/nodets/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - mongo

    mongo:
        container_name: mongo-docker
        image: mongo
        volumes:
            - ./data/db:/data/db
        ports:
            - "27017:27017"

networks:
    local-network:
        driver: bridge
